University/Models/CardViewModel.cs
namespace University.MVC.Models;

public class CardViewModel
{
    public int? Id { get; set; }
    public string Title { get;set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string FirstName { get; set; } = string.Empty;
    public string LastName { get; set; } = string.Empty;
    public int GroupID { get; set; }
    public int? CourseID { get; set; }

    public string InfoURL { get; set; } = string.Empty;
    public string DownTitle { get; set; } = string.Empty;    
    public string DownURL { get; set; } = string.Empty;

    public int NumPages { get; set; }
}

University/Models/ErrorViewModel.cs
namespace University.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

University/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using University.Models;
using University.Infrasructure.Services;
using University.Infrasructure.Models;
using University.MVC.Models;

namespace University.Infrasructure.Controllers;

public class CoursesController : Controller
{

    private const int COURSES_ON_PAGE = 8;
    private readonly ICourseService _courseService;

    private readonly CourseModel _courseModel;
    private readonly CardViewModel _viewModels;
    

    public CoursesController(ICourseService courseService, CourseModel courseModel)
    {
        _courseService = courseService ?? throw new ArgumentNullException(nameof(courseService));
        _courseModel = courseModel ?? throw new ArgumentNullException(nameof(courseModel));
        _viewModels = new CardViewModel();
    }

    public IActionResult ListEntities(int? page)
    {
        int numPages = (int)Math.Ceiling((decimal)_courseService.Count() / COURSES_ON_PAGE);
        int currentPage = page ?? 1;
        int skip = (currentPage - 1) * COURSES_ON_PAGE;
        int take = COURSES_ON_PAGE;

        var listCourses = _courseService.ListEntities(skip, take);
        var model = (listCourses, numPages, currentPage);

        return View(model);
    }

    public IActionResult InfoCourse(int Id)
    {
        return View(_courseService.InfoCourse(Id));

    }


    [HttpGet]
    public IActionResult EditCourse(int? Id)
    {
        if (Id != null & Id != 0)
        {
            return View(_courseService.InfoCourse(Id.Value));
        }
                    
        return View(_courseService.AddCourse());
    }

    [HttpPost]
    public IActionResult EditCourse(CourseModel course)
    {
        _courseService.SaveCourse(course);

        TempData["message"] = $"Course \"{course.Name}\" saved!";

        return RedirectToAction("ListEntities");
    }


    public IActionResult DeleteCourse(int Id)
    {
        bool isDeleted = _courseService.DeleteCourse(Id);
        if (isDeleted)
        {
            TempData["message"] = $"Course deleted";
        }
        else
        {
            TempData["message"] = $"Course not deleted because it is not empty!";
        }

        return RedirectToAction("ListEntities");
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

University/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;
using University.Infrasructure.Models;
using University.Infrasructure.Services;
using University.Models;

namespace MVC.Controllers;

public class GroupsController : Controller
{
    private const int GROUPS_ON_PAGE = 8;

    private IGroupService _groupService;
    private ICourseService _courseService;
    

    public GroupsController(IGroupService groupService, ICourseService courseService)
    {
        _groupService = groupService ?? throw new ArgumentNullException(nameof(groupService));
        _courseService = courseService ?? throw new ArgumentNullException(nameof(courseService));
    }

    public IActionResult ListEntities(int? Id, int? page)
    {
        int numPages = (int)Math.Ceiling((decimal)_groupService.Count(Id) / GROUPS_ON_PAGE);
        int currentPage = page ?? 1;
        int skip = (currentPage - 1) * GROUPS_ON_PAGE;
        int take = GROUPS_ON_PAGE;

        var listGroups = _groupService.ListEntities(Id, skip, take);
        var model = (listGroups, numPages, currentPage);

        return View(model);
    }    

    public IActionResult InfoGroup(int Id)
    {
        return View(_groupService.InfoGroup(Id));
    }

    [HttpGet]
    public IActionResult EditGroup(int? Id)
    {
        var courses = _courseService.GetAllCourses().ToList();
        int coursesCount = courses.Count;
        ViewBag.ListCourses = new SelectList(courses, "Id", "Name");
        if (Id != null & Id != 0)        
            return View(_groupService.InfoGroup(Id.Value));
        
            if(coursesCount > 0)
            return View();

        TempData["message"] = $"you can't create a group while no courses exist. Create a course first";
        return RedirectToAction("ListEntities");
    }

    [HttpPost]
    public IActionResult EditGroup(GroupModel group)
    {
        _groupService.SaveGroup(group);

        TempData["message"] = $"Group \"{group.Name}\" saved!";

        return RedirectToAction("ListEntities");
    }


    public IActionResult DeleteGroup(int Id)
    {
        bool isDeleted= _groupService.DeleteGroup(Id);
        if (isDeleted)
        {
            TempData["message"] = $"Group not deleted because it is not empty!";
        }
        
        TempData["message"] = $"Group deleted";

        return RedirectToAction("ListEntities");
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

University/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;
using University.Infrasructure.Models;
using University.Infrasructure.Services;
using University.Models;

namespace Students_MVC.Controllers;

public class StudentsController : Controller
{
    private const int STUDENTS_ON_PAGE = 8;
    private IStudentService _studentService;
    private IGroupService _groupService;

    public StudentsController(IStudentService studentService, IGroupService groupService)
    {
        _studentService = studentService ?? throw new ArgumentNullException(nameof(studentService));
        _groupService = groupService ?? throw new ArgumentNullException(nameof(groupService));
    }  

    public IActionResult ListEntities(int? parentGroupId, int? page)
    {
        int numPages = (int)Math.Ceiling((decimal)_studentService.Count(parentGroupId) / STUDENTS_ON_PAGE);
        int currentPage = page ?? 1;
        int skip = (currentPage - 1) * STUDENTS_ON_PAGE;
        int take = STUDENTS_ON_PAGE;        

        var listStudents = _studentService.ListEntities(parentGroupId, skip, take);
        var model = (listStudents, numPages, currentPage);

        return View(model);
    }

    public IActionResult InfoStudent(int Id)
    {
        return View(_studentService.InfoStudent(Id));
    }


    [HttpGet]
    public IActionResult EditStudent(int? Id)
    {
        var groups = _groupService.GetAllGroups().ToList();
        int groupsCount = groups.Count;
        ViewBag.ListGroups = new SelectList(groups, "Id", "Name" );
        if (Id != null & Id != 0)
            return View(_studentService.InfoStudent(Id.Value));

        if (groupsCount > 0)
            return View();

        TempData["message"] = $"you can't create a student while no groups exist. Create a group first";
        return RedirectToAction("ListEntities");
    }

    [HttpPost]
    public IActionResult EditStudent(StudentModel student)
    {
        _studentService.SaveStudent(student);

        TempData["message"] = $"Student \"{student.FirstName}, {student.LastName} \" saved!";

        return RedirectToAction("ListEntities");
    }


    public IActionResult DeleteStudent(int Id)
    {
        _studentService.DeleteStudent(Id);
        TempData["message"] = $"Student deleted";

        return RedirectToAction("ListEntities");
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

University/Views/Courses/EditCourse.cshtml
@model University.Infrasructure.Models.CourseModel


@using (Html.BeginForm())
{

    @Html.HiddenFor(m => m.Id)

    <label>Course Name</label>
    @Html.EditorFor(m => m.Name)

    <label>Course Description</label>
    @Html.EditorFor(m => m.Description)    

    <input type="submit" value="Save"/>
}

University/Views/Courses/InfoCourse.cshtml
@model University.Infrasructure.Models.CourseModel;

@{
    ViewData["Title"] = "Course info";
}

<h1>@ViewData["Title"]</h1>


<div class="container">

    @{
var cardModel = new University.MVC.Models.CardViewModel
    {
        Title = $"Course ID: {Model.Id}",
        Name = $"Course name: {Model.Name} ",
        Description = $"About: {Model.Description}",
        InfoURL = Url.Action("EditCourse", "Courses", new { Id = Model.Id }),
        DownTitle = "Students",
        DownURL = Url.Action("DeleteCourse", new { Id = Model.Id })
    };
    }

    @Html.Partial("_CardEditDelete", cardModel)

</div>

University/Views/Courses/ListEntities.cshtml
@model (IEnumerable<University.Infrasructure.Models.CourseModel> ListCourses, int NumPages, int CurrentPage)


@{
    ViewData["Title"] = "Courses";
}

<h1>@ViewData["Title"]</h1>

<a href="@Url.Action("EditCourse", "Courses")">Add course</a>

@if (TempData["message"] != null)
{
    <div class="TempMessage">@TempData["message"]</div>
}

<div class="container">

    @foreach (var course in Model.ListCourses)
{
    var cardModel = new University.MVC.Models.CardViewModel
            {
                Title = course.Name,
                Description = course.Description,
                InfoURL = Url.Action("InfoCourse", "Courses", new { Id = course.Id }),
                DownTitle = "Groups",
                DownURL = Url.Action("ListEntities", "Groups", new { Id = course.Id })
            };

    @Html.Partial("_CardInfoEdit", cardModel)

}
</div>

<div class="pagination">
    @await Html.PartialAsync("_PagedList", (Model.NumPages, Model.CurrentPage))
</div>

University/Views/Groups/EditGroup.cshtml
@model University.Infrasructure.Models.GroupModel;


@using (Html.BeginForm())
{
    @Html.HiddenFor(m=>m.Id)

    <label>Group Name</label>
    @Html.EditorFor(m=>m.Name)

    <label>Course Name</label>    
    @Html.DropDownListFor(m => m.CourseID, (IEnumerable<SelectListItem>)ViewBag.ListCourses)

    <input type="submit" value="Save"/>
}

University/Views/Groups/InfoGroup.cshtml
@model University.Infrasructure.Models.GroupModel;

@{
    ViewData["Title"] = "Group info";
}

<h1>@ViewData["Title"]</h1>


<div class="container">

    @{
var cardModel = new University.MVC.Models.CardViewModel
{
    Title = $"Group ID: {Model.Id}",
    Description = $"Group name: {Model.Name}",
    CourseID = Model.CourseID,
    InfoURL = Url.Action("EditGroup", "Groups", new { Id = Model.Id }),
    DownTitle = "Students",
    DownURL = Url.Action("DeleteGroup", new { Id = Model.Id })
};
    }

    @Html.Partial("_CardEditDelete", cardModel)

</div>

University/Views/Groups/ListEntities.cshtml
@model (IEnumerable<University.Infrasructure.Models.GroupModel>GroupsList, int NumPages, int CurrentPage)

@{
    ViewData["Title"] = "Groups";
}

<h1>@ViewData["Title"]</h1>


<a href="@Url.Action("EditGroup", "Groups")">Add group</a>

@if (TempData["message"] != null)
{
    <div class="TempMessage">@TempData["message"]</div>
}

<div class="container">

    @foreach (var group in Model.GroupsList)
{
    var cardModel = new University.MVC.Models.CardViewModel
            {
                Title = $"Group {group.Id}",
                Description = group.Name,
                InfoURL = Url.Action("InfoGroup", "Groups", new { Id = group.Id }),
                DownTitle = "Students",
                DownURL = Url.Action("ListEntities", "Students", new { Id = group.CourseID })
            };

    @Html.Partial("_CardInfoEdit", cardModel)
}
</div>

<div class="pagination">
    @await Html.PartialAsync("_PagedList", (Model.NumPages, Model.CurrentPage))
</div>

University/Views/Shared/_CardEditDelete.cshtml
@model University.MVC.Models.CardViewModel



<div class="courseWrapper">

    <div class="course">
        @Model.Title
       
        <br/> @Model.Description
        <br/> @Model.FirstName
        <br/> @Model.LastName
    </div>
    <div class="bottons">
        <div class="infoButton" onclick="location.href = '@Model.InfoURL';" style="cursor: pointer">Edit</div>        
        <div class="nestedListBotton" onclick="if(confirm('Are you sure?')){ location.href = '@Model.DownURL'; }" style="cursor: pointer">Delete</div>

        
    </div>
</div>

University/Views/Shared/_CardInfoEdit.cshtml
@model University.MVC.Models.CardViewModel

<div class="courseWrapper">

    <div class="course" >
        <b>@Model.Title</b><br /> @Model.Description
    </div>
    <div class="bottons">
        <div class="infoButton" onclick="location.href = '@Model.InfoURL';" style="cursor: pointer">Info</div>
        <div class="nestedListBotton" onclick="location.href = '@Model.DownURL';" style="cursor: pointer">@Model.DownTitle</div>
    </div>
</div>

University/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - University</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/University.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Courses" asp-action="ListEntities">University</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="ListEntities">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Groups" asp-action="ListEntities">Groups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="ListEntities">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - University - <a asp-area="" asp-controller="Courses" asp-action="ListEntities">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

University/Views/Shared/_PagedList.cshtml
@model (int NumPages, int CurrentPage)


@{
    int currentPage = Model.CurrentPage;
int totalPages = Model.NumPages;
    string Controller = this.ViewContext.RouteData.Values["controller"]?.ToString();
    int previous = 0;
int next = 0;
}

@if (totalPages <= 5)
{
    @for (int i = 1; i <= totalPages; i++)
{
    @if (i == currentPage)
    {
        <span>@i</span>
    }
    else
    {
        <a href="@Url.Action("ListEntities", Controller, new { Page = i })">@i</a>
    }
}
}
else
{
    @*@for (int i = 1; i <= totalPages; i++)
    {*@
previous = currentPage - 1;
next = currentPage + 1;

    @if (currentPage < 2)
{
    <text>1</text>
    <a href="@Url.Action("ListEntities", Controller, new { Page = 2 })">2</a>
    <a href="@Url.Action("ListEntities", Controller, new { Page = 3 })">3</a>
    <text> ... </text>
    <a href="@Url.Action("ListEntities", Controller, new { Page = totalPages })">@totalPages</a>

}
else if (currentPage < totalPages - 1)
{
    <a href="@Url.Action("ListEntities", Controller, new { Page = previous })">@previous</a>
    <span>@currentPage</span>
    <a href="@Url.Action("ListEntities", Controller, new { Page = next })">@next</a>
    <text> ... </text>
    <a href="@Url.Action("ListEntities", Controller, new { Page = totalPages })">@totalPages</a>
}
else if (currentPage == totalPages - 1)
{
    <a href="@Url.Action("ListEntities", Controller, new { Page = previous })">@previous</a>
    <span>@currentPage</span>
    <text> ... </text>
    <a href="@Url.Action("ListEntities", Controller, new { Page = totalPages })">@totalPages</a>

}
else if (currentPage >= totalPages)
{
    <a href="@Url.Action("ListEntities", Controller, new { Page = 1 })">1</a>
    <text> ... </text>
    <a href="@Url.Action("ListEntities", Controller, new { Page = previous })">@previous</a>
    <span>@currentPage</span>
}
}





@*else
    {
        <a href="@Url.Action("ListEntities", Controller, new { Page = totalPages })">@totalPages</a>
    }
    @*}*@












@*@if (currentPage >= 2 || currentPage != totalPages)
        {
            previous = currentPage - 1;
            next = currentPage + 1;

            if (currentPage != 1)
            {
                <a href="@Url.Action("ListEntities", Controller, new { Page = previous })">@previous</a>
            }
            <text>@currentPage</text>

            if (currentPage + 1 != totalPages || currentPage - 1 != totalPages || currentPage != totalPages)
            {
                <a href="@Url.Action("ListEntities", Controller, new { Page = next})">@next</a>
            }


        }
        else
        {
            <text>1</text>
            <a href="@Url.Action("ListEntities", Controller, new { Page = 2 })">2</a>
            <a href="@Url.Action("ListEntities", Controller, new { Page = 3 })">3</a>
        }

        <span>...</span>

        @if (currentPage == totalPages)
        {
            <span>@currentPage</span>
        }

        else
        {
            <a href="@Url.Action("ListEntities", Controller, new { Page = totalPages })">@totalPages</a>
        }*@

University/Views/Students/EditStudent.cshtml
@model University.Infrasructure.Models.StudentModel;


@using (Html.BeginForm())
{
    @Html.HiddenFor(x=>x.Id)

    <label>Student`s first name</label>
    @Html.EditorFor(x=>x.FirstName)

    <label>Student`s last name</label>
    @Html.EditorFor(x=>x.LastName)

    <label>Group name</label>
    
    @Html.DropDownListFor(m => m.GroupID, (IEnumerable<SelectListItem>)ViewBag.ListGroups)

    <input type="submit" value="Save" />
}

University/Views/Students/InfoStudent.cshtml
@model University.Infrasructure.Models.StudentModel;

@{
    ViewData["Title"] = "Student info";
}

<h1>@ViewData["Title"]</h1>

<div class="container">

    @{
var cardModel = new University.MVC.Models.CardViewModel
    {
        Title = $"Student Id: {Model.Id}",
        FirstName = $"Name: {Model.FirstName}",
        LastName = $"Soname: {Model.LastName}",
        InfoURL = Url.Action("EditStudent", "Students", new { Id = Model.Id }),
        DownTitle = "Students",
        DownURL = Url.Action("DeleteStudent", new { Id = Model.Id })
    };
    }

    @Html.Partial("_CardEditDelete", cardModel)

</div>

University/Views/Students/ListEntities.cshtml
@model (IEnumerable<University.Infrasructure.Models.StudentModel>StudentsList, int NumPages, int CurrentPage)

@{
    ViewData["Title"] = "Students";
}

<h1>@ViewData["Title"]</h1>

<a href="@Url.Action("EditStudent", "Students")">Add student</a>

@if (TempData["message"] != null)
{
    <div class="TempMessage">@TempData["message"]</div> 
}

<div class="container">

    @foreach (var student in Model.StudentsList)
{
var cardModel = new University.MVC.Models.CardViewModel
        {
            Title = $"Student {student.Id}",
            FirstName = student.FirstName,
            LastName = student.LastName,                    
            InfoURL = Url.Action("InfoStudent", "Students", new { Id = student.Id }),
            
        };

    @Html.Partial("_CardInfoEdit", cardModel)

}
</div>

<div class="pagination">
    @await Html.PartialAsync("_PagedList", (Model.NumPages, Model.CurrentPage))
</div>